import Navbar from "../../components/section/Navbar";
import "./globals.css";
import { Cabin, Cormorant, Inter, Lato, Sora } from "next/font/google";
import Footer from "../../components/section/Footer";
import { CartContextProvider } from "../providers/CartContext";
import { useState } from "react";
import Link from "next/link";
import { MenuIcon } from "lucide-react";
import Menu from "components/section/Menu"; 
import { MenuProps } from "components/section/Menu";
import { fetchCategories, fetchLogo } from "./data";
import { PImage } from "./utils/types";
// import {headers} from "next/headers";

export const lato = Lato({
  subsets: ["latin"],
  weight: "900",
});

export const cabin = Cabin({
  subsets: ["latin"],
  weight: "400",
});

export const sora = Sora({
  subsets: ["latin"],
  weight: "700",
});

export const sora_light = Sora({
  subsets: ["latin"],
  weight: "400",
});

export const sora_d = Sora({
  subsets: ["latin"],
  weight: "600",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   viewport: {
//     content: "width=device-width",
//     initialScale: 1.0,
//   },
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await fetchCategories();
  const { logo }: any = await fetchLogo();
  // const headersList = headers();
  // const pathname = headersList.get("next-url");
  // console.log(pathname);
  console.log('children', children);
  return (
    <html lang="en">
      <body className="my-[2rem] space-y-[5rem]">
        <CartContextProvider>
          <Navbar navLinks={categories} logo={logo} />
          {children}
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
