import Navbar from "components/section/Navbar";
import "@/app/globals.css";
import { Cabin, Cormorant, Inter, Lato, Sora } from "next/font/google";
import Footer from "components/section/Footer";
import { CartContextProvider } from "../../providers/CartContext";
import { fetchCategories, fetchLogo } from "../data";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { fetchCartItems, fetchCartProducts } from "./server";
import { Toaster } from "react-hot-toast";
import { CartProduct } from "@/reducer/CartReducer";

export const lato = Lato({
  subsets: ["latin"],
  weight: "900",
});

export const cabin = Cabin({
  subsets: ["latin"],
  weight: "400",
});

export const sora = Sora({
  subsets: ["latin"],
  weight: "700",
});

export const sora_light = Sora({
  subsets: ["latin"],
  weight: "400",
});

export const sora_l = Sora({
  subsets: ["latin"],
  weight: "300",
});

export const sora_d = Sora({
  subsets: ["latin"],
  weight: "600",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   viewport: {
//     content: "width=device-width",
//     initialScale: 1.0,
//   },
// };

const fetchContextData: (_user_id:string|null) => Promise<{
  cartItems: number;
  cartProducts: CartProduct[],
  total: number
}> = async (_user_id:string|null) => {
  if (_user_id === null) {
    return {
      cartItems: 0,
      cartProducts: [],
      total: 0,
    };
  } else {
    const {cartProducts, total} = await fetchCartProducts(_user_id);
    return {
      cartItems: await fetchCartItems(_user_id),
      cartProducts: cartProducts,
      total: total,
    };
  }
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await fetchCategories();
  const { logo }: any = await fetchLogo();
  const { userId } = auth();
  const {cartItems, cartProducts, total} = await fetchContextData(userId);

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className="my-[2rem] space-y-[5rem]"
          suppressHydrationWarning={true}
        >
          <CartContextProvider
            cart_items={cartItems !== null ? Number(cartItems) : 0}
            cart_products={cartProducts}
            _total={total}
          >
            <Navbar navLinks={categories} logo={logo} key={logo.asset.url} />
            <Toaster position="top-center"/>
            {children}
            <Footer />
          </CartContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
